### PR TITLE
Rev. v3_5 for 'Radiological Model v3' for HD 1x2x6 (fcl and producer) to address Wire-Cell reco issue

### PR DESCRIPTION
**Pull request by jurgenr2023**
Revision v3_5 for new assays based 'Radiological Model v3' for HD 1x2x6, HD 1x2x2 and VD 1x8x6 (requiring corresponding producer files). 
[As APA electronics boards in geometry break Wire-Cell reco, added fix for those backgrounds, independent now of boards being present in geometry]
-Juergen Reichenbacher (SDSMT) 2023/12/11

### CODE REVIEW

**Comment by absolution1** [comment]
I've created a PR for this against my fork here: https://github.com/absolution1/dunesim/pull/2

We'll get this PR merged there and then merge into dune/dunesim

**Comment by jurgenr2023** [comment]
Thanks Dom!

**Review by tomjunk — APPROVED** [review]
Looks okay, though there is a lot of duplication of what's already in dune_radiological_model.   Some people ask about the sheet of concrete in the middle of an APA, though it is a conservative stand-in for cryostat and cavern radiologicals.  That sheet of concrete appears in many places now, but since we have 1x2x2 and 1x2x6, that may be unavoidable.

**Comment by absolution1** [comment]
Hi @tomjunk 
Can the merge be backed out?  It was supposed to be a closed PR.  I'd moved it over to my fork as per my comment above.  We'll be issuing a new PR after some refactoring.

**Pull request merged**
