### PR TITLE
New background model (v3.6) and new configs for 2 separate active volumes in HD

### PR DESCRIPTION
**Pull request by lpaulucc**
Adding the new radiological decay0 model v3.6 for HD and VD.
Also adding the necessary changes to work with the modifications introduced in https://github.com/DUNE/dunecore/pull/107 where the active volume in HD is divided into two separate volumes so we can switch off the energy deposits in half of it to emulate the lateral APA with the current geo.
Together, a new config to generate MARLEY events in only half the active volume in HD.

(STILL UNDER DEVELOPMENT)

### CODE REVIEW

**Review by tomjunk — APPROVED** [review]
Looks fine

**Review by tomjunk — COMMENTED** [review]
Is this still under development?

**Comment by tomjunk** [comment]
Holding off merging until hearing back from Laura.

**Comment by lpaulucc** [comment]
Hi Tom, I am still waiting on the new background flux files so we can put them in StashCache. There may be some tweaks needed here after that as well. So if we can hold this a little longer (hopefully we will hear from the LE people next week) that would be great. Thanks!

**Comment by tomjunk** [comment]
@lpaulucc Did the LE people get the background flux files in StashCache?  Were the tweaks needed?

**Comment by lpaulucc** [comment]
Let's go ahead and merge it. Thank you, Tom!

**Pull request merged**
