### PR TITLE
Update dunevd larg4 detector service 

### PR DESCRIPTION
**Pull request by jroto**
Change the dunevd larg4 detector service parameters from volExternalActive, to volCryostat, in order to simulate energy deposits in the full liquid argon volume. This PR is related with a PR in dunecore: https://github.com/DUNE/dunecore/pull/61

### CODE REVIEW

**Review by lpaulucc — COMMENTED** [review]
Hi José, I took the opportunity to make a change that I needed in the ion and scint file. Please check if you are ok with my new commit.

**Review by jroto — COMMENTED** [review]
Looks good to me!

**Comment by lpaulucc** [comment]
Ok, so now we just need to adjust what is needed for the old geometries to run and that is set

**Comment by tomjunk** [comment]
Is this PR ready to go, or is there further adjustment needed for old geometries?

**Comment by jroto** [comment]
> Is this PR ready to go, or is there further adjustment needed for old geometries?

No is not, this PR contains the changes needed for geometry v5, but we are still using v4 as default. This should be merged once the default geometry is set to v5.

**Comment by lpaulucc** [comment]
Jose, what if we include the active volumes automatically? Even when we officially move to v5, it would be important to have things working for older geometries since they are being used for official VD MC productions.

**Comment by lpaulucc** [comment]
I see the problem... The `dunefdvd_ionandscint_external` is used with the semi-analytical model because it needs a photon library behind the field cage... we could include the correct volume for older geometries in the running fhicl file (or put a message in the wiki that someone wanting to run older geos need to do this). Let's think a little about it and make some tests with the new semi-analytical model that I hear is almost done.

**Comment by lpaulucc** [comment]
Jose, Jiaoyang made some of the changes that are in this PR (sorry I asked her to do it because I forgot about this one). But reviewing her PR, I think some of the changes you were including in larg4services_dune.fcl should not be done since we are not really making changes to the older geometries. Can you please take a look at her PR (https://github.com/DUNE/dunesim/pull/40) and check the changes that will be needed in here not to have conflicts?

**Comment by lpaulucc** [comment]
I only remember updating the 3view_30deg geometry (not 2 view or 3view) in latest changes. In any case, Jiaoyang's dunecore PR (https://github.com/DUNE/dunecore/pull/69) only makes v5 the default for the 3view_30deg 1x8x14 geo (we will need to wait the LBL production to be over to update the 1x8x6).

**Comment by lpaulucc** [comment]
No, we can't remove this PR because of the changes in the IonAndScint, that are not in Jiaoyang's PR

**Review by lpaulucc — APPROVED** [review]
Thanks, Jose!

**Pull request merged**
