### PR TITLE
Hybrid model for ProtoDUNE-HD

### PR DESCRIPTION
**Pull request by Li-Jiaoyang97**
Created scintillation and ionisation instances for the hybrid model, with ProtoDUNE-HD v3 geometry.

### CODE REVIEW

**Review by lpaulucc — COMMENTED** [review]
Hi Jiaoyang, don't you also need to define LArG4Detector somewhere?

**Comment by Li-Jiaoyang97** [comment]
Hi Laura @lpaulucc, I think [here](https://github.com/DUNE/dunesim/blob/6e72667f8982c1d68ef005c23866b48b67328ec7/dunesim/Simulation/larg4services_dune.fcl#L141-L147) is where I defined the LArG4Detector. Let me know if I am missing something, thanks.

**Comment by lpaulucc** [comment]
In the old days of the legacy LArG4, we had to set in the services fcl something like
`LArG4Detector: @local::yourlarg4definition`
Maybe you can check with a fhicl-dump what it is being set for this

**Comment by Li-Jiaoyang97** [comment]
Hi @lpaulucc, yes the declaration is in [dunecore](https://github.com/DUNE/dunecore/blob/bb19b1fbb4f5cac2b1a7577ca9e1ed839e32c2bc/dunecore/Utilities/services_refactored_pdune.fcl#L32).  
Somehow you were not the reviewer of my PR, I just corrected this. Sorry about this.

**Review by lpaulucc — APPROVED** [review]

**Pull request merged**
